### ISSUE TITLE
fresh install

### ISSUE THREAD

**Issue by aeonabyss** [modhunter/NerdPack-NoC#14]
Message: ..\AddOns\NerdPack-NoC\core.lua line 70:
   attempt to index field 'Timer' (a nil value)
Debug:
   NerdPack-NoC\core.lua:70: in main chunk
Locals:
Parse = nil
Fetch = <function> defined @Interface\AddOns\NerdPack\interface\tools.lua:649
shuffleTable = <function> defined @Interface\AddOns\NerdPack-NoC\core.lua:41
MasterySpells = <table> {
 116847 = ""
 107428 = ""
 100784 = ""
 115080 = ""
 113656 = ""
 115098 = ""
 152175 = ""
 117952 = ""
 123986 = ""
 100780 = ""
 101545 = ""
 101546 = ""
 205320 = ""
}
HitComboLastCast = ""
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = "attempt to index field 'Timer' (a nil value)"

**Comment by modhunter** [comment]
Hi,
- Which combat rotation are you selecting?
- Which version of NerdPack is installed?

I haven't seen this issue and use the monk rotations every day so this is strange.  Are you able to successfully use any of the other combat routines?

**Comment by aeonabyss** [comment]
After posting that last night the DH Veng routine still seemed to work.
Idk why that was popping up for it.  I'm using stable release 70.5

**Comment by modhunter** [comment]
Is still still an issue for you?

**Comment by aeonabyss** [comment]
No idea. Switched to 1.5 and the only ones that work are Xeer and MTS

**Comment by modhunter** [comment]
Try getting from the 1.5 branch for NoC (https://github.com/modhunter/NerdPack-NoC/tree/1.5).  Won't merge to master till it's fully working as well as before.

**Comment by modhunter** [comment]
1.5 stuff is merged to master. Re-open if you still have problems
