### ISSUE TITLE
NP1.5

### ISSUE THREAD

**Issue by JerkWang** [modhunter/NerdPack-NoC#16]
V1.5 cuts out your rotations... how do I make them visible again?

**Comment by modhunter** [comment]
You can use MTS's PR (https://github.com/modhunter/NerdPack-NoC/pull/15) but if you're using the windwalker routine, two important capabilities (automatic dotting for SCK and hit combo buff maintenance) were removed as part of this update.

I won't be updating myself to 1.5 until I can get back this functionality that was lost.

**Comment by modhunter** [comment]
You can find the 1.5 compatible code in the 1.5 branch here: https://github.com/modhunter/NerdPack-NoC/tree/1.5

If you use Windwalker, it will be broken in the fact that it won't perform hit combo properly which is a flat 16% DPS loss.
